# Generated by Django 2.1.1 on 2018-09-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20180917_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='country',
            new_name='mid',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rated',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='year',
        ),
        migrations.AlterField(
            model_name='moviegenre',
            name='genre',
            field=models.CharField(max_length=20),
        ),
    ]
