# Generated by Django 2.1.1 on 2018-09-19 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20180919_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='imbVotes',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='production',
        ),
    ]
