# Generated by Django 2.1.1 on 2018-09-19 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20180919_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imbdID',
            new_name='imdbID',
        ),
    ]
