# Generated by Django 2.1.1 on 2018-09-24 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0006_auto_20180921_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.BooleanField()),
                ('watched', models.BooleanField()),
                ('watch_later', models.BooleanField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Favourite',
            new_name='Trending',
        ),
        migrations.RemoveField(
            model_name='watched',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='watched',
            name='user',
        ),
        migrations.RemoveField(
            model_name='watchlater',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='watchlater',
            name='user',
        ),
        migrations.DeleteModel(
            name='Watched',
        ),
        migrations.DeleteModel(
            name='WatchLater',
        ),
    ]
