# Generated by Django 2.1.1 on 2018-09-24 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_popular'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlist',
            old_name='favorite',
            new_name='favourite',
        ),
    ]
