# Generated by Django 2.1.1 on 2018-09-26 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20180926_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popular',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trending',
            name='user',
        ),
    ]
