# Generated by Django 2.1.1 on 2018-09-27 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_auto_20180926_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='based_on',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='based_on_which_movie', to='movies.Movie'),
        ),
    ]
