//Navbar actions
export const NAV_SEARCH = 'NAV_SEARCH'
export const NAV_SEARCH_SCREEN = 'NAV_SEARCH_SCREEN'
export const NAV_SEARCH_LOADING = 'NAV_SEARCH_LOADING'

// Fetch Movies
export const FETCH_POPULAR = 'FETCH_POPULAR'
export const FETCH_FAVORITE = 'FETCH_FAVORITE'
export const FETCH_WATCHED = 'FETCH_WATCHED'
export const FETCH_WATCHLATER = 'FETCH_WATCHLATER'
export const FETCH_TRENDING = 'FETCH_TRENDING'



